package cpusimulator;

import java.util.ArrayList;
import java.util.StringTokenizer;

/**
 * This dialog used to edit asm source. It have just one multilined textarea and two buttons: OK and Cancel.
 * OK button causes acceptAction to be activated, and Cancel button causes cancelAction like that.
 * 
 * @author Daniel Alexandre 2011
 */
public class AsmSourceDialog extends javax.swing.JDialog {
    
    /** Action which will be activated by Cancel button clicking. It can be specified by a parameter in constructor. */
    private Runnable cancelAction;
    /** Action which will be activated by Accept button clicking. It can be specified by a parameter in constructor. */
    private Runnable acceptAction;

    /**
     * Creates new assembler code edit dialog. It just have a single textarea editor to edit simple text.
     * @param parent parent form to use modality
     * @param modal modality will be used if this argument will be true
     * @param cancelAction callable object to handle Accept button click
     * @param acceptAction callable object to handle Cancel button click
     * @throws NullPointerException if one of actions is null
     */
    public AsmSourceDialog(java.awt.Frame parent, boolean modal, Runnable cancelAction, Runnable acceptAction) {
        super(parent, modal);
        initComponents();
        
        // copy handlers to class fields and check it for null
        if((this.cancelAction = cancelAction) == null) throw new NullPointerException();
        if((this.acceptAction = acceptAction) == null) throw new NullPointerException();
    }
    
    /**
     * Sets assembler lines to text field. It should be called before showing this dialog.
     * @param assemblerCode string array with lines which contains assembler instructions (1 instr. per line)
     */
    public void setAsmLines(String[] assemblerCode) {
        // just concatenate lines into one buffer and sets buffer contents to textarea
        StringBuilder builder = new StringBuilder();
        for(String line : assemblerCode) builder.append(line).append("\n");
        jTextArea1.setText(builder.toString());
    }
    
    /**
     * Returns assembler lines, typed/modified by user.
     * @return string array with lines which contains assembler instructions (1 instr. per line)
     */
    public String[] getAsmLines() {
        // get the text, split it into lines array
        String text = jTextArea1.getText();
        StringTokenizer tokenizer = new StringTokenizer(text, "\n");
        ArrayList<String> lines = new ArrayList<String>();
        while(tokenizer.hasMoreTokens()) {
            String token = tokenizer.nextToken().trim();
            if(!token.isEmpty()) lines.add(token); // add if and only if line isn't empty, so we treat empty lines as comments
        }
        String[] linesArray = new String[lines.size()];
        for(int i = 0; i < lines.size(); i ++) linesArray[i] = lines.get(i);
        return linesArray;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Assemble");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // just run cancel action
        cancelAction.run();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // just run accept action
        acceptAction.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // treat as cancel action
        setVisible(false);
        cancelAction.run();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
